# Пользователи
## Создать нового пользователя

POST http://localhost:4010/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "name": "Jefrey Epstine",
  "password": "shining"
}

###

## Авторизовать пользователя

POST http://localhost:4010/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "password": "shining"
}

###

## Проверить токен пользователя
GET http://localhost:4010/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJuYW1lIjoiSmVmcmV5IEVwc3RpbmUiLCJpZCI6IjZhMDA4NGFhNzljNDhkMmUyOTJlMGM1OCIsImlhdCI6MTc3ODQ5ODQ3NCwiZXhwIjoxNzc4NjcxMjc0fQ.A69V54CeazbTUb55s_LHSFHnmwDJ4DIjavrclZuLmjI

###
